sudo:required
services:
  - docker

before_install:
  - docker build -t rush/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rush/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"  
  bucket_name: "elasticbeanstalk-us-east-2-128424116548"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"